### ISSUE TITLE
a release please

### ISSUE THREAD

**Issue by farooqkz** [HassanHeydariNasab/roboto#1]
Hi, if this is a game please release it(including 32-bit Linux binary).
P.S.: as a baby, I like toys...

**Comment by HassanHeydariNasab** [comment]
Hi,
This is my first practice of creating game by Godot. First page of my workbook. :D
OK, bro!

**Comment by farooqkz** [comment]
P.S.: also for your newsly created repo(birdo3d?)

**Comment by HassanHeydariNasab** [comment]
it's only a prototype now.
